version: '3'
services:

  composer_cli:
    image: fabric/composer-cli
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
    working_dir: /root/hyperledger/composer
    command: 
    volumes:
      - ./:/root/hyperledger/composer
      - ./.composer:/root/.composer
      #- ./ledger/ca-DOMAIN:/etc/hyperledger/fabric-ca-server
    hostname: composer-cli
    networks:
      byh:
        aliases:
          - composer-cli
networks:
  byh:
    external:
      name: byh
