# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # AbcInsurer
  # ---------------------------------------------------------------------------
  - Name: AbcInsurer
    Domain: AbcInsurer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
